### ISSUE TITLE
Reorder factors of category in dittoHeatmap legend?

### ISSUE THREAD

**Issue by ms-gx** [dtm2451/dittoSeq#110]
Is it possible to reorder the factors of a category in the legend of a dittoHeatmap graph?

If yes, how do I approach this?

**Comment by dtm2451** [comment]
Not the same way as in other dittoPlotters, and I'm not sure how to build a nice UX for that in dittoHeatmap, but the reorder inputs inside dittoSeq are mainly for convenience anyway...

What you can do outside of dittoSeq (*not just for dittoHeatmap*) is reorder the levels of that data within your `object` itself using the base fxn `factor`.

So for example, for a categorical metadata 'groups' with values "level1", "level2", and "level3"...

```
new_groups <- factor(my_object$groups, levels = c("level3", "level2", "level1"))
# Check this before moving on, perhaps with `table(new_groups)`

my_object$groups_reordered <- new_groups

# That change should inherit into any subsequent dittoSeq (or other) function.
dittoHeatmap(my_object, ..., annot.by = "groups_reordered")
```

Just be sure to check the `new_groups` before replacing your old metadata, or store the reordered data in a new metadata slot as I do above, because if you miss or mistype any levels that were in the data, you'll end up with NAs!

**Comment by ms-gx** [comment]
Thank you! I'll try this.
