### ISSUE TITLE
boxplot p-value significance indicator?

### ISSUE THREAD

**Issue by levinhein** [dtm2451/dittoSeq#113]
Hello. May I ask if there's a functionality for p-value significance indicator between boxplots?

I made a split boxplot of gene signature split by Healthy, Disease, and Recovery. I wonder if this is something possible. Thank you!

**Comment by dtm2451** [comment]
Hey there!  Glad you were able to make your intended plot!  I'll close #111 after merging #112.

To answer this question:  There is nothing built in for stats currently, and I don't plan to add anything either.  See below for why.

In order to add statistics to your plots, I recommend checking out the `ggpubr` package, and in particular the `stat_compare_means` function, if it can handle your case, or the `stat_pvalue_manual` function + manually calculating statistics, if it cannot.  I've used this package myself in conjunction with using the `max` input of `dittoPlot()`/`dittoBoxPlot()` to make the extra room needed for stat bars in the plots.

#### Why is no p-value calculation automation planned?

I've thought about this a lot before.  I know stat bars would be very useful, especially for users without the ggplot know-how to customize their plots and add stats on their own afterwards.  But unfortunately, I've come to the conclusion that it wouldn't be a good idea to build.  The defaults would be too hard to get right and that's pretty problematic on its own.  Plus there would likely be confusingly many user-interface options required.

Actually determining the proper statistical test to use for a given comparison can be quite hard, and likely impossible to automate within dittoSeq. Thus any defaults I'd set would be wrong often.  This is a HUGE problem to me because dittoSeq aims to be usable by biologists at various stages of training, and that means there will be many without the statistical training to determine if a t-test vs wilcoxon vs anova is the right test type.  In many cases, even if I indicated "Use caution!" in the function documentation, such users won't notice that and will assume that because dittoSeq let them calculate statistics, that those statistics are proper.  Such plots might then make it into publications cuz we all know peer review isn't perfect.  I don't dittoSeq to be a cause of that.

Then there's also the input side of designing how users would state which groups to compare to which other groups + how to show.  And I think that would get confusing and colmplicated too.  For example, in your case above you probably want to compare healthy <=> disease and disease <=> recovery, but you may or may not want to compare healthy <=> recovery.  Or, since I think you're plotting expression of multiple based on your previous issue, #111, do you want to compare healthy-gene1 <=> healthy-gene2?  Or maybe even everything-gene1<=> everything-gene2?
