### ISSUE TITLE
`scales = "free"` not properly respected in `split.adjust` when multiple vars provided to dittoPlot (and co)

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#114]
```
dittoPlot(sce, c("sum", "detected", "subsets_Mito_percent"), group.by = "Sample", 
               legend.show = FALSE, split.adjust = list(scales = "free"))
```
![image](https://user-images.githubusercontent.com/10225716/181799978-9a754552-d3d0-436e-8b7d-47a45b8d10bc.png)

The y-axis is drawn for each facet, but the scale isn't adjusted for each.

**Comment by dtm2451** [comment]
Hmmm.  I think here it's that there's an explicit call to `coord_cartesian()` to apply `min` and `max` to the y-axis regardless of whether the user gave a `min` or `max`, b/c that code got more complicated than I like, even without making the `coord_cartesian()` addition conditional.

But I can abstract all of it into a separate function...

I've had plenty of occasions to want `scales = free` to work too, so I think it's worth it to make work since it's not just me.  :+1: thanks for another good poke!

**Comment by dtm2451** [comment]
Correction: The real problem here was really just that most of the `min`/`max` code was written pretty naively when I wasn't as good with ggplot2 =p.

Can you try with the 'min-max-reduce-impact' branch?  `remotes::install_github("dtm2451/dittoSeq@min-max-reduce-impact")`

**Comment by j-andrews7** [comment]
Sorry, been busy, this did indeed work well for me. Closin'.
