### ISSUE TITLE
have x-values sort numerically?

### ISSUE THREAD

**Issue by organicbrownrice** [dtm2451/dittoSeq#120]
<img width="859" alt="image" src="https://github.com/dtm2451/dittoSeq/assets/123776503/1e8d499e-f4f5-4060-9f49-78df1de2c397">

Is there any way to sort the cluster numbers by increasing value instead of what the default is?

Here is the code I ran to produce to graph.
dittoBarPlot(HS.combined.CellCount, "ident", group.by = "HS.combined",
             scale = "count")

**Comment by dtm2451** [comment]
Hey there!

Should be a simple fix seeing as you're targeting "ident" and Seurat normally does make the clustering metadata this will grab a factor ordered from 0 to the highest cluster number.... Just add `retain.factor.levels = TRUE` to your call.

I made the (probably incorrect looking back) choice to favor aligning with previous default functionality when I built this respect-for-factor-levels functionality into dittoBarPlot.  And so I set the default for this input to FALSE.  But probably 99% of use cases for dittoBarPlot would prefer `retain.factor.levels = TRUE`, so when I do get to build dittoSeq-v2, this'll become the default setting rather than something which needs to be turned on!

**Comment by dtm2451** [comment]
Ahhh you may need to make your 'HS.combined' metadata a factor with levels ordered as desired, too.

Something like this should work for that!

```
HS.combined.CellCount$HS.combined <- factor(
    HS.combined.CellCount$HS.combined,
    levels = sort(as.numeric(unique(HS.combined.CellCount$HS.combined)))
)
```

**Comment by organicbrownrice** [comment]
Thank-you so much for your quick response! The updated code worked for me :)
