### ISSUE TITLE
working with altExps

### ISSUE THREAD

**Issue by cstrlln** [dtm2451/dittoSeq#126]
Hello,
wondering if you have a suggestion on how to best use dittoseq for accesing the info on altExps in SCE objects. For example how to plot data from protein, Cite-seq -like experiments? 
Thank you for any advice.

**Comment by dtm2451** [comment]
Unfortunately, there's not much built for altExps at the moment, so immediate answer: I think the best way to work with these would be to extract your altExp data into a separate SCE, and visualize from that.

**But this is a hole I'd love to close** which primarily exists because of a lack of understanding on my end of how altExps work and get used (I've done all my CITEseq work in Seurats so far.).  If you'd be able to share a paired-down / anonymized version of your SCE (my email is in my profile if you want to share more privately), or just point me to a good alternate example dataset to learn from, that'd help me get started.

**Comment by cstrlln** [comment]
I was thinking about just completely separating the data for now, thanks for the feedback!
Yes, I will get a small dataset for you and will followup by email.

**Comment by dtm2451** [comment]
Just adding, I'd been noodling about allowing joint targeting of RNA+ADT data, at least for the Seurat objects where I know better how to allow it, since before you opened this issue.  It's underway in #128!  So you asked this with impeccable timing.

**Comment by dtm2451** [comment]
Looked up the accessor functions and seemed pretty doable to implement, so instead of sending me your data in some way, maybe you can install via `remotes::install_github('dtm2451/dittoSeq@genes-accross-seurat-assays')` and test directly?

## How I've implemented it so far, but feel free to comment if you hate it:
If the data you want grabbed is the first assay in your target altExp, then you can just give the altExp's name (or 'altexp' for the first altExp in the object) to the `assay` input via, e.g. `assay = 'ADT'` or `assay = 'altexp'`.  If you need to target a specific assay within the altExp, then give the assay you want to access named as the altExpName you want to access via `assay = c(<altExpName or altexp> = <assayName>)`.

### Examples using `getGenes()`, but it works the same in any of the plotters:
```
library(dittoSeq)
library(SingleCellExperiment)

# Creating a quick SCE with 2 alternate experiments, the first unnamed, and the second named 'ADT'.
# Both have 2 assays: 1 - 'counts', 2 - 'logcounts'
example("importDittoBulk", echo = FALSE)
altExp(myRNA) <- myRNA[34:66,]
altExp(myRNA, 'ADT') <- myRNA[67:100,]
myRNA <- myRNA[1:33,]

# Retrieves from the first alternate experiment, and would retrieve from its first assay ('counts' here)
getGenes(myRNA, assay = 'altexp')
# Retrieves from the first alternate experiment, and its assay named logcounts
getGenes(myRNA, assay = c(altexp = 'logcounts'))
# Retrieves from the alternate experiment named 'ADT', and its first assay ('counts' here)
getGenes(myRNA, assay = 'ADT')
# Retrieves from the alternate experiment named 'ADT', and its assay named logcounts
getGenes(myRNA, assay = c(ADT = 'logcounts'))
# Retrieves from the alternate experiment named 'ADT', and its second assay ('logcounts' here)
getGenes(myRNA, assay = c(ADT = 2))
```

## Multi-Assay Access
Since the same PR also implements multi-assay access, if you want to make a dittoDotPlot with both RNA and ADT data all in one plot, you can do that by giving it your needed equivalent of `assay = c('normcounts', adt = 'normcounts')` or similar!

**Comment by cstrlln** [comment]
Works great for plotting with dittodim as well.
Will let you know if encounter any issue down the road.

Thanks so much!

**Comment by cstrlln** [comment]
Actually, did run into an issue. Was trying to run an scatter plot like this:

dittoSeq::dittoScatterPlot(
    object = sce2,
    x.var = "ENSG00000117322", y.var = "Hu.CD21",
    color.var = "sorted_cell_type",
    assay = c('logcounts', adt = 'logcounts'))

gets this error:

Error in dittoSeq::dittoScatterPlot(object = sce2, x.var = "ENSG00000117322",  : 
  argument 5 matches multiple formal arguments

**Comment by dtm2451** [comment]
Ahh that's because the assay input of dittoScatterPlot is a bit different... for flexibility-sake, I built it to let you use different assays for x, y, color, extra-data grabbing (probs uncommun), and hover.data.

So you need this here instead of just `assay`:
`assay.x = c('logcounts', adt = 'logcounts'), assay.y = c('logcounts', adt = 'logcounts')`

**Comment by cstrlln** [comment]
I see, that makes sense.
Sorry I'm trying to understand the naming. If my altExp is called 'CSP' would the assay slot be called with:
assay.x = c('logcounts', CSP = 'logcounts'), assay.y = c('logcounts', CSP = 'logcounts').

I'm guessing the first logcounts refers to the main experimente (e.g. gene expression slot)
or is 'adt' a generic way to called the first altExp?

**Comment by dtm2451** [comment]
> Sorry I'm trying to understand the naming. If my altExp is called 'CSP' would the assay slot be called with:
> assay.x = c('logcounts', CSP = 'logcounts'), assay.y = c('logcounts', CSP = 'logcounts')

Yep! and....

> I'm guessing the first logcounts refers to the main experimente (e.g. gene expression slot)

yep! but...

>or is 'adt' a generic way to called the first altExp?

nope.  'altexp' is the generic way to access the first altExp.  'ADT' was my altExpName example.

Sorry for confusion... I'll definitely be doing a few more passes on the explanation for the documentation in the package!

**Comment by cstrlln** [comment]
Great, it worked.

Here is an example of how it worked for me, in case someone else reads this:

dittoSeq::dittoScatterPlot(
    object = sce2,
    x.var = "CR2", y.var = "Hu.CD21",
    color.var = "sorted_cell_type",
    assay.x = c('logcounts'),
    assay.y = c(CSP = 'logcounts'),
    swap.rownames = 'Symbol')

One last question, and I know this is likely too much to ask but: here I used the swap.rownames to find the right name in the main object, is there a way to also specify the location of rowData in the altExp? as altExp also can contain multiple names for genes e.g. ID, Symbol, etc.

**Comment by dtm2451** [comment]
Great question, and thanks for posting this example!

`swap.rownames` is a spot I haven't finished figuring out how I'll update to work with the now potentially multiple rowData() targets.  Currently, there is no swap.rownames implementation added for the for altExp side at all.  Since it's relevant to you, I'll update you again here once I do implement it.  Feel free to leave the issue open until that's done too as this is not too much to ask, and also still very relevant to the issue title =)

Edited with what I've made so far: 'Simple' way swaps across all rowData. 'Explicit' way uses names for specifying the main-assay/altExp-linkage. So for your example above, if you wanted to swap to the 'Symbol' column from any of the main or alt experiments that have it, `swap.rownames = 'Symbol'` would work.  If you wanted to swap to 'Symbol' or 'ID' columns that exist (priority to the earlier one if both exist in the same rowData) in the main or any alternate experiments, you could do `swap.rownames = c('Symbol', 'ID')`. If there's need to be fully explicit, you can do that too by using names and 'main' for the main / non-alternate experiment via `swap.rownames = c(main = 'Symbol', CSP = 'ID')` . And another explicit example, if you only wanted to swap for the main assays, `swap.rownames = c(main = 'Symbol')` would do that.

**Comment by dtm2451** [comment]
swap.rownames bit is implemented!

I've edited the explanation in the comment above to match how I set it up to work.  Thinking I'll devote a whole documentation page to explaining the altExp gene-grabbing and rowname swapping mechanics... A bit complicated now to explain, but it should be a system that's easy to use once learned!

Let me know if you have any questions.

**Comment by cstrlln** [comment]
Thank you, that was so fast.
Which version should I reinstall?

**Comment by dtm2451** [comment]
=) you should reinstall from the same too-narrowly-named branch as before... `remotes::install_github('dtm2451/dittoSeq@genes-accross-seurat-assays')`.
