### ISSUE TITLE
Changing titles on multi-plots / pseudo facet titles

### ISSUE THREAD

**Issue by Varix** [dtm2451/dittoSeq#131]
fantastic agnostic visualization package

I was thinking of diving into the code to make a push to add the feature of renaming the titles in facet plots when you have multiple features in a  `dittoBoxPlot` etc or multiple `group.by` as attempting to manually edit the `labeller` in `facet_wrap` /  `facet_grid` , breaks the entire ditto plot...

before I get too deep into the custom functions you have written for facet'ing plots to add this title change feature, I was wondering, is there already an easy way to edit or add custom titles either through ggplot or facet_grid attributes? dont want to do all this work if everyone else already has an easy solution I haven't thought of. 

Thanks!

**Comment by Varix** [comment]
okay so some trial and error, you can just replace `dittoSeq` plots custom facets with default `ggplot` ones as long as you also provide every condition required and not just replacing the ones you want to change. Its an all or nothing, but it works.  this is easier than adding a new attribute and changing the facet function in the package.

**Comment by dtm2451** [comment]
Hey there, thanks for the idea and kind words =).

If you wouldn't mind sharing an example of your working code, this sounds like a useful idea for users to be able to search!  Or possibly one that I could implement via some input in a future update.

Second, since you mention 'agnostic' visualization package, just in case you meant 'data agnostic' I wanna point you to [dittoViz](https://github.com/dtm2451/dittoViz) where I have been pulling out the basic visualization capabilities from the (sc)Seq data grabbing features to make a visualization suite that starts more simply with data.frame-like objects.
