### ISSUE TITLE
Change colors of genes in dittoHeatmap

### ISSUE THREAD

**Issue by aditisk** [dtm2451/dittoSeq#135]
Hello,

I am trying to change the colors of certain genes I would like to group using a named vector of colors but that is not working for me. I tried using the `annotation_colors` argument but that doesn't seem to be working for me. What is the proper way to change colors of certain genes in the heatmap ? Thanks

**Comment by dtm2451** [comment]
The way `annotation_colors` works, per pheatmap's docs:
> list for specifying annotation_row and annotation_col track colors manually. It is possible to define the colors for only some of the features. Check examples for details.

The easiest way to give it in my experience has been:
```
annotation_colors = list(
    <name-of-annotation-set> = c(<value1>=<color1>, <value2>=<color2>, <value3>=<color3>)
)
```

Specific Qs / Suggestions:

1- Are you giving an `annotation_row` in order to demarcate how you want genes colored?  There's no functionality built in to `dittoHeatmap()` for annotation of genes/rows (at the moment), so the way to start this is by building your `annotation_row` input separately.  Then you can use `annotation_colors` or `annot.colors` to set your coloring.

2a- If yes, the \<name-of-annotation-set\> in my above `annotation_colors` example would be your annotation_row colname(s), the \<value#\> would be the actual underlying values of those columns, and \<color#\> should be the color your want to use for said values.

2b- If yes, alternatively, you can make use of dittoSeq's automated color picking, but it's not as explicit so I do recommend setting up an `annotation_colors` directly. Details: dittoSeq's internal system creates (or adds to) `annotation_colors` for any annotation set not already given in `annotation_colors`.  The colors it picks come from the vector of colors given to the `annot.colors` input.  So you can give a vector of colors of your choice to `annot.colors`, and dittoHeatmap will assign colors from this vector 1-by-1 per any annotation-sets without colors already defined.  (It pulls from the start of the vector for discrete annotations, and the end of the vector for continuous annotations.)  Happy to help toward this route too.  Just, in addition to the less-explicit nature of this method, I'm also hesitant to suggest this method because I'm not sure how good the built-in error messaging is for failures within this color assignment system.

**Comment by aditisk** [comment]
Hi @dtm2451,

Thank you so much for the detailed response. I was using `annotation_row` and `highlight.features` to select the genes of interest. I followed suggestion 2a and I was able to add a column annotation (heatmap attached) but not change the color of the gene names itself. I was hoping to change the color of the gene itself. I found this example using pheatmap (https://svsuresh.github.io/pheatmap_change_rowcolors),  but was having a hard time replicating it since the output of the dittoHeatmap() is slightly different than the standard pheatmap output I think. Any thoughts/suggestions on this? Thanks.

![heatmap](https://github.com/dtm2451/dittoSeq/assets/15878219/f5cf7814-3fcf-418b-a1f9-49ff6fb847aa)

**Comment by dtm2451** [comment]
Sounds like I misunderstood what you wanted.  And you now have what I thought you wanted working, yet not what you actually wanted.

The bulk of dittoHeatmap() code builds inputs for pheatmap (either the pheatmap package version or more recently alternatively the ComplexHeatmap::pheatmap() version).  And then its final lines either pass those inputs to one of these pheatmap functions and directly output the return, or else output the inputs that were prepped if you'd set `data.out = TRUE`.

That is to say 1) the output you are getting from `dittoHeatmap()` should be consistent with any standard output of `pheatmap()`, and 2) you can make use of `data.out = TRUE` to build your own `pheatmap()` calls directly by using the `mat` plus in whatever other elements you want from what dittoHeatmap preps for you.

Perhaps this is an issue of interference from additional features on pheatmap's end?  As far as I can tell, this issue may extend past features that I've built into dittoSeq.  You could use `dat <- dittoHeatmap(..., data.out = TRUE)` and try again with the minimal output of running `pheatmap(dat$mat)`.

The issue could also relate to your use of `highlight.features`.  When using that, you will see a `labels_row` among the args generated for you because the way this input is implemented is by adjusting plot labels to be empty strings for all non-highlighted features, via the `labels_row` pheatmap input.

**Comment by dtm2451** [comment]
Closing, but feel free to reopen if help is still needed.
