### ISSUE TITLE
Dotplot on single gene split by two conditions

### ISSUE THREAD

**Issue by ramadatta** [dtm2451/dittoSeq#141]
Hi,

Thank you very much for the nice tool!

May I know, how to resolve this error, if I want to plot only one gene?

```
> cd_genes <- c("Zfp646")
> dittoDotPlot(data, cd_genes, group.by = "compartment_label",split.by = "age")
Error in .multi_var_gather_raw(object, vars, assay, slot, adjustment,  : 
  'vars' must be a vector of at least two elements for this function.
```

many thanks in advance!

**Comment by dtm2451** [comment]
Unfortunately, you can't.  The way the color/size calculation is done requires a substantial enough re-design for using a single `vars` that I'd decided, when I added this `'vars' must be a vector of at least two elements for this function.` error that you are seeing, to trim that from the scope of the plotter.

You can get around it by picking a second gene, and then ignoring the second gene in your analysis...

At the time I made this scoping decision, I didn't think a use-case existed where a single-var dot plot would be ideal.  But maybe that's incorrect?  Is this single-var version something that you think you ultimately need here?  Or alternatively, is this *just* the "temporary" way you've currently conceived to answer your analysis question, in which case adding a second gene would be functionally okay?

**Comment by ramadatta** [comment]
Hi @dtm2451,

thank you so much for swift reply.

I am actually plotting a single gene dotplot for my shiny app, where users click on a gene in the datatable row and see their dotplot updated for the specific gene expression in the both conditions.

I could not find a workaround using `seurat dotplot` which is why I was appreciating dittoseq. When I have conditions like in my case, age (young and old), `dittoseq` nicely generates a `facet_wrap` but only with atleast 2 genes.

In such a scenario, adding a second gene does not seem to help. I would like to hear if you have any suggestions or advice!

Many thanks again!

P.S: Found an similar thread describing the [issue](https://github.com/satijalab/seurat/issues/5117) and this is discussed [here](https://github.com/samuel-marsh/scCustomize/issues/152#issue-2052538011) as well:

**Comment by dtm2451** [comment]
It's not supported directly with the function, but because you can get the underlying data from all dittoSeq visualizations, you can access the data behind the dots to build your own plot.  So my suggestion is to make us of dittoDotPlot with `data.out = TRUE` and a dummy 2nd gene (or a numeric metadata for this to make avoiding clash with user input easier!).  Then build your own dot plot.  

Most basic:
```
example("importDittoBulk", echo = FALSE)
df <- dittoDotPlot(myRNA, c("gene1", "score1"), "groups", split.by = "conditions", data.out = TRUE)$data
ggplot(
    data = df[df$var=="gene1",],,
    aes(var, grouping, fill = color, size = size)) +
    geom_point() +
    facet_wrap(~conditions)
```

Grabbing a few extra dittoSeq adds that I notice are missing right away, but you may want to poke through the code as I'm sure I'm missing more!:
```
example("importDittoBulk", echo = FALSE)
df <- dittoDotPlot(myRNA, c("gene1", "score1"), "groups", split.by = "conditions", data.out = TRUE)$data
ggplot(
    data = df[df$var=="gene1",],
    aes(var, grouping, color = color, size = size)) +
    geom_point() +
    facet_wrap(~conditions) +
    # Note that when 'scale' = FALSE, this color title should be "Average\nExpression" instead
    scale_color_gradient(name = "Relative\nExpression", low = "grey90", high = "#C51B7D") +
    scale_size_continuous(name = "Percent\nExpression") +
    theme_classic()
```
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/a6e319dd-4161-42ea-8f24-1ed79114a78f)

**Comment by dtm2451** [comment]
It's not supported directly with the function, but because you can get the underlying data from all dittoSeq visualizations, you can access the data behind the dots to build your own plot.  So my suggestion is to make us of `dittoDotPlot()` with `data.out = TRUE` and a dummy 2nd gene (or a numeric metadata for this to make avoiding clash with user input easier!).  Then build your own dot plot.  

Most basic:
```
example("importDittoBulk", echo = FALSE)
df <- dittoDotPlot(myRNA, c("gene1", "score1"), "groups", split.by = "conditions", data.out = TRUE)$data
ggplot(
    data = df[df$var=="gene1",],,
    aes(var, grouping, fill = color, size = size)) +
    geom_point() +
    facet_wrap(~conditions)
```

Grabbing a few extra dittoSeq adds that I notice are missing right away, but you may want to poke through the code as I'm sure I'm missing more!:
```
example("importDittoBulk", echo = FALSE)
df <- dittoDotPlot(myRNA, c("gene1", "score1"), "groups", split.by = "conditions", data.out = TRUE)$data
ggplot(
    data = df[df$var=="gene1",],
    aes(var, grouping, color = color, size = size)) +
    geom_point() +
    facet_wrap(~conditions) +
    # Note that when 'scale' = FALSE, this color title should be "Average\nExpression" instead
    scale_color_gradient(name = "Relative\nExpression", low = "grey90", high = "#C51B7D") +
    scale_size_continuous(name = "Percent\nExpression", limits = c(0.001,NA)) +
    theme_classic()
```
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/7611c6bb-3fdd-4fed-88c6-47232f4b8710)

**Comment by dtm2451** [comment]
PS, I'm not choosing to support this internally because my opinion is that violin plots are better for single genes.  In dittoSeq, you would achieve that with `dittoPlot()`, which also gets access to the `split.by` functionality you are using here to show age.  Although with that function, you could opt to put your groups in `color.by` and age in `group.by`.  You might like that output more as it provides more detail.

**Comment by ramadatta** [comment]
hi @dtm2451 ,

Many thanks for this, I kind of used code similar to yours to fetch the data and plotted using ggplot. This issue can be closed for now.
