### ISSUE TITLE
dittoHeatmap

### ISSUE THREAD

**Issue by Aminach1** [dtm2451/dittoSeq#143]
Hallo and thanks for the great package!

I wanted to create a heatmape, here is my code: 

dittoHeatmap(sce_data, genes = markers,  assay = "exprs",
             heatmap.colors = viridis(100), 
             annot.by = c("FastPG_clusters", "sample_id"))

I don't know exactly what's going wrong, but the result looks like this
![file_show](https://github.com/dtm2451/dittoSeq/assets/152868589/4175c299-4253-46f6-aeb2-c9b4dae9f72e)

Can you help me? Thanks very much

**Comment by dtm2451** [comment]
Hmmm, that's certainly not right!

I feel like I've seen something like this before, and the cause may have been some missing data, but I don't remember.

You can try investigating by adding `data.out = TRUE` to your dittoHeatmap call and also storing the result (`args <- dittoHeatmap(..., data.out = TRUE)`, can use anything, but `args` is the variable name I'll use below.) to explore its elements afterwards. For this function, doing so gives you the args list that would otherwise get passed to `pheatmap()` via `do.call(pheatmap::pheatmap, args)`.
1. Do you still get a blank heatmap if you then run just `pheatmap::pheatmap(args$mat)`?
2. And if so, do `any(is.na(args$mat))`, `any(is.infinite(args$mat))`, or `any(is.nan(args$mat))` give TRUE?

Alternatively, another quick thing to try is to add `complex = TRUE` to your `dittoHaatmap()` function call which switches the function over to making use of `ComplexHeatmap::pheatmap()` at its end.  This different heatmap engine might give informative errors/warnings in spots where `pheatmap::pheatmap()` does not.

**Comment by Aminach1** [comment]
Hello, and thanks very much for your reply. 

1. when I run pheatmap::pheatmap(args$mat), i get an error: cannot allocate vector of size 65594.7 Gb
2. No, all the three of them give FALSE
I still get a blank heatmap when trying data.out = TRUE or complex = TRUE.
Is this related to the fact that the data is large? When subsampling the data, I was able to generate a heatmap with a few cells (0.1 % of the dataset).

**Comment by dtm2451** [comment]
Oh, could be related to data size... That sounds like it fits the bill.  How many cells?  It does sound like the internal calculations run fine (see correction for my direct pheatmap call suggestion below!), so perhaps your system, or RStudio, is giving up on figuring out how to display the many thousands of color boxes while rendering the heatmap?

In addition to downsampling, which never feels like my favorite option, one other thing you can try would be to make use of ComplexHeatmap's rasterization capabilities.  [Book docs for rasterization with ComplexHeatmap](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#heatmap-as-raster-image).  A quick check of if this might help would be to try:

```
dittoHeatmap(sce_data, genes = markers, assay = "exprs",
    heatmap.colors = viridis(100),
    annot.by = c("FastPG_clusters", "sample_id"),
    complex = TRUE, raster_resize_mat = TRUE
)
```

To my understanding, `raster_resize_mat = TRUE` simplifies the matrix to plot by using a `mean` call per each set of matrix segments that would become the same pixel.  If that works, you can make the rasterization less drastic by using other options in that package -- I just figure this method can serve as a positive control for "Can rastering help?" =).

You may still need `raster_resize_mat = TRUE` if your data is truly gigantic, but adding something like `raster_quality = 5` could decrease the internal pixel-ization and let the image be prettier and somewhat amenable to zoom/rescaling. 
 (Extra inputs given to dittoHeatmap get passed along to the chosen `<tool>::pheatmap()` function.  This is why you can give them directly.  Here, the `raster_resize_mat` input goes through to `ComplexHeatmap::pheatmap()` which then passes it on to its own `ComplexHeatmap::Heatmap()` internal.)

1. I'd forgotten about the default of all clustering being "on" in `pheatmap::pheatmap()`.  That's where your 'cannot allocate vector of size...' error is coming from. I bet if you ran `pheatmap::pheatmap(args$mat, cluster_cols = FALSE)` it'd give a similar story to your regular dittoHeatmap outputs.

**Comment by dtm2451** [comment]
Very curious if you have gotten a chance to try this heatmap generation with the matrix simplification afforded by adding `complex = TRUE, raster_resize_mat = TRUE` per my message above!  I think that's a likely fix, and would confirm pretty well if dataset size (at plot render-time) was at fault!

**Comment by dtm2451** [comment]
Still curious whether you have been able to try the raster-related suggestions I gave above?

But I'm going to close this issue due to inactivity and as it does not seem to reflect a bug with dittoSeq itself.

For you or anyone else hitting a similar situation in the future, although it's not confirmed I still believe fiddling with `ComplexHeatmap` raster options, per my comments above, would help!
