### ISSUE TITLE
Support for Seurat V5?

### ISSUE THREAD

**Issue by RoseString** [dtm2451/dittoSeq#145]
Dear dittoSeq developer,

DittoSeq has been a invaluable tool in my research, and upgrading to Seurat V5 will unfortunately lose its compatibility. I was wondering if a support for V5 is under development? 

Thanks again for such a useful tool!

Dan

**Comment by dtm2451** [comment]
As far as I knew, I have already made dittoSeq compatible with Seurat V5!

Did you get a warning or something saying otherwise?  Or did you run into an error which you think is a compatibility issue?  If so, please share your error details and what version of dittoSeq, `packageVersion("dittoSeq")`, you are using!

**Comment by RoseString** [comment]
That's awesome. I upgraded Seurat to V5 a few months ago, and it was not compatible with dittoSeq, so I reverted to V4 and haven't tried again since. I saw in dittoSeq's README that it's compatible with V2,3,4 and thought it's still not V5-compatible. But great to know! I'll try it. Thanks for the continued maintenance!:)

**Comment by dtm2451** [comment]
Oh!  I'll update that bit in the README.  Had just forgotten about that note, so thanks for this reminder =)
