### ISSUE TITLE
Marker disappeared in the heatmap

### ISSUE THREAD

**Issue by giuliospinozzi** [dtm2451/dittoSeq#146]
When I try to generate the first heatmap with the following code (image attached):

`dittoHeatmap(spe[,cur_cells], treeheight_row=0,  treeheight_col=0, genes = rownames(spe)[rowData(spe)$use_channel], assay = "exprs", cluster_cols = F, scale = "none", heatmap.colors = colorRampPalette(colors = turbo_colormap_data_HEX)(100), annot.by = "patient_id", annotation_colors = list(patient_id = col_sample_id),clustering_callback = callback_rev)`

Sometimes a specific marker is not printed (but in the rowData(spe) is present). Privately we can discuss (I would not public our data here)

**Comment by dtm2451** [comment]
Hi there,

Because you have `genes = rownames(spe)[rowData(spe)$use_channel]`, you are only requesting plotting of markers that both exist ("in the rowData(spe) is present") and ALSO have `TRUE` in the `rowData(spe)$use_channel`.  I expect markers not getting printed are FALSE in the use_channel rowData column.  You can give simply `genes = rownames(spe)` to avoid this secondary marker filtration.

Hope this helps!
-Dan

**Comment by giuliospinozzi** [comment]
Thanks, but the problem persists... 
We are investigating also in the data structure before, where we select samples and markers.

**Comment by giuliospinozzi** [comment]
I have the reason. Was the hot pixel filter with tophat.
Thanks for the help, we can close.
