### ISSUE TITLE
White line on heatmap

### ISSUE THREAD

**Issue by shengyongniu** [dtm2451/dittoSeq#148]
Hi there,
I'm using dittoHeatmap and put two layers of labels on top of it. However, I'm not sure why there are white lines on the labels. I've checked that there are no NA values in the metadata. There is no white line if I just use one of the layers for annot.by and order.by. Any suggestion? Thank you

dittoHeatmap(subset(obj, downsample = 500, seed=999), gene, 
             annot.by = c("A","B"), order.by = c("A","B"),
             breaks=seq(-4, 4, length.out=50))

<img width="1312" alt="image" src="https://github.com/dtm2451/dittoSeq/assets/10880134/198ccd23-e12a-499c-8426-e0b99c1ecd1b">

**Comment by dtm2451** [comment]
Very odd.  The regular spacing of the lines makes me think it might be a rendering glitch in RStudio, or however it's getting plotted, rather than something generated by dittoHeatmap or the pheatmap plotter used internally.  Does changing the size of the plot window (or the resolution of your output file) affect it?

**Comment by shengyongniu** [comment]
Thanks for your fast reply! I changed the size of the plot window and the white lines do disappear, but then the texts become too crowded. Let me play with it. Thank you!
