### ISSUE TITLE
Error in .subscript.2ary(x, i, j, drop = TRUE) : subscript out of bounds

### ISSUE THREAD

**Issue by shengyongniu** [dtm2451/dittoSeq#149]
Hi there,

I first run ScaleData on seurat object then run the dittoHeatmap for plotting. Any suggestion? Thank you!

obj <- ScaleData(optic_nerve)
dittoHeatmap(subset(obj, downsample = 300, seed=999), feature_gene, 
             annot.by = c(A,B), order.by = c(A,B),
             breaks=seq(-4, 4, length.out=50))

Error in .subscript.2ary(x, i, j, drop = TRUE) : subscript out of bounds

**Comment by dtm2451** [comment]
I need more info to be able to understand where this is error would be coming from.

Perhaps an element of `feature_gene` doesn't exist in your expression matrix?

But based on the `dittoHeatmap()` code you have given, the fact that you ran `ScaleData()` should not matter because dittoHeatmap() will use the 'data' slot by default, not the 'scale.data' slot that I do not recommend pointing it to anyway (per my comment [here](https://github.com/dtm2451/dittoSeq/issues/127#issuecomment-1719572176)).
