### ISSUE TITLE
dittoHeatmap : Error in .var_OR_get_meta_or_gene(x, object, assay, slot)

### ISSUE THREAD

**Issue by BaluPai** [dtm2451/dittoSeq#150]
Hi,

I am getting an error while trying the following:

dittoHeatmap(obj,
             genes = NULL,
             metas = (c("HALLMARK-HYPOXIA","HALLMARK-GLYCOLYSIS")),
             heatmap.colors = rev(colorblind_vector(50)),
             annot.by = c("region","patient"),
             cluster_cols = TRUE,
             fontsize = 7)
Error in .var_OR_get_meta_or_gene(x, object, assay, slot) : 
  region is not a gene of the targeted assay(s), a metadata, nor equal in length to ncol('object')

I checked the metadata:
........[321] "HALLMARK-FATTY-ACID-METABOLISM"             "HALLMARK-G2M-CHECKPOINT"                   
[323] "HALLMARK-GLYCOLYSIS"                        "HALLMARK-HEDGEHOG-SIGNALING"               
[325] "HALLMARK-HEME-METABOLISM"                   "HALLMARK-HYPOXIA"...............

It used to work earlier on our HPC server with Seuratv4.3./R 4.2.2. Currently trying on Seurat v5/R4.3

I am using ESCAPE package and also have this data added as an Assay to my Seurat object.

Please advise!

Thanks a lot

**Comment by dtm2451** [comment]
Hi there,

The error message here starts with your offending metadata-ask and it's **region** rather than one of the pathways. 
Maybe I should add `'`s around it here to highlight that bit better in this error message generation :shrug:. 

Seems that metadata might be missing from your current version of the object?  You can try again with just `annot.by = c("patient")` or run `isMeta("region", obj)` to confirm!

Best,
Dan

**Comment by BaluPai** [comment]
Thanks so much Dan!
My bad, you are right. That worked.
And thanks for this easy tool for visualization.
