### ISSUE TITLE
Support plotting trajectory curves on dittoDimPlot

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/DittoSeq#18]
The ability to plot lineage trajectories via `dittoDimPlot` is excellent, but do you have any plans to add trajectory curves as well? This should be fairly trivial to [add](https://ggplot2.tidyverse.org/reference/geom_path.html).

**Comment by dtm2451** [comment]
I do not currently, but am open to suggestions for how I might do so.

dittoDimPlot currently allows plotting of trajectories over any dimensionality reduction using straight lines between clusters in the trajectory paths.  That is as far as I had planned because median cluster centers are easy to calculate, and afterwards, the method for making a straight line between points is unambiguous.  There is little methods ambiguity here except in that median is what's used for picking the clusters' centers.

Currently, as far as I have experience at least, trajectory analysis packages tend to only calculate smoothed curves for certain dimensionality reductions.  Because there are many options for how to calculate such curves, I do not plan to make dittoSeq into a calculation tool for new curve paths at this time.

That said, I supposed a method for extraction and plotting of calculated curves is possible.  `geom_path` is the geom already used for plotting trajectories, so I suppose that all adding this feature would require conceptually is a method to accept manually provided paths.  Perhaps with a list structure similar to the current `add.trajectories` but with:

- `add.manual.trajectories.x` & `add.manual.trajectories.y` = list of vectors, one for each separate trajectory, of x and y coordinates, that the curves should follow
- `manual.trajectory.arrow.size` = size of the arrows

Does that sound like a useful method?

**Comment by j-andrews7** [comment]
I've submitted #19 to handle this for `slingshot` output. Does no calculations, just grabs the curve coordinates and plots them.
