### ISSUE TITLE
Code organization suggestions

### ISSUE THREAD

**Issue by LTLA** [dtm2451/DittoSeq#3]
From a quick scan of the code, here's some immediate structural suggestions:

- I would strongly consider breaking up the `DittoSeq.R` file into smaller chunks. I know it's convenient to have all the functions in a single file, but this becomes unsustainable as your package gets larger and you have to keep on jumping up and down in the same file, e.g., to edit a function that gets called by another function. I usually have a single function definition per file, or at least a single category of function definitions; this makes it easier to navigate.
- Your functions are designed to work with a range of input classes - this is prime territory for S4 dispatch. In some sense, you're already doing that in functions like `get.genes`, so it would be less effort to just let the dispatch system do that for you automatically. More generally, it's good to learn, because S4 is a powerful system that allows you to do pretty awesome things. (Not in this particular use case, but it really gets going when you deal with data infrastructure.)
- Keep an eye on the complexity of your function interfaces. Developers (i.e., yourself) will find the code difficult to reason about if they have to worry about the combinatorial effects of multiple arguments. If there are no combinatorial effects, that should be enforced by splitting the code into multiple subfunctions that do separate parts. As a rough guideline, you should aim to keep functions below 50 lines of code; this is a very loose guideline, but ~250 for `DBDimPlot` is probably too long. It's not the worst I've seen, though; our `iSEE` function was several thousand lines long to handle the observer code... and it sucked to work on.

Some more specific coding suggestions, taken pretty much from `BiocCheck`:

- Don't access slots directly, i.e., don't use `@` or `slot()`. This is a pretty common problem that causes havoc with user code when the internal representation of the class changes. (Case in point, Seurat v2 to v3.) Rather, use the accessor functions if they have been provided - if not, write your own so that you quarantine any `@` calls to a few functions that are easy to change.
- Don't use `F` or `T`. `T <- FALSE` works, for example - and it's not even that uncommon (e.g., if you're working with Brachyury, or Hotelling's T).
-  Avoid `1:n`, use `seq_len(n)`. Similarly, use `seq_along(vec)` instead of `1:length(vec)`. The replacements have an advantage in that they behave sensibly when `n=0`.

That should probably be enough to get you going.

**Comment by dtm2451** [comment]
Thank you for all these suggestions!

I've now:
- broken the code into chunks based on which type of plot a function generates.  A helper / data-grabbing functions are still in DittoSeq.R, but I can subset those further too in the future.
- changed all my `T` and `F`  to `TRUE` and `FALSE`
- replaced all `1:length(X)` to `seq_along(X)` or `1:dim(X)[1/2]` with `seq_len(dim(X)[1/2])`
- reduced slot access without accessor functions / written and used my own accessor functions.

Still To Do:
- Learn how to utilize S4 dispatch and implement it to simplify my code =).
- Make my functions shorter.  I find it hard in many of my visualizations because my goal is generally to make many tweaks possible through simple inputs.  This often does lead to combinatorial effects that require separate if/then/else and code repeats with respective tweaks, but a 50 or 100 line maximum is certainly a goal on my horizon when possible.
- Check again that I use accessor functions whenever possible and confine `@` usage to only my accessor functions.

**Comment by LTLA** [comment]
> * I find it hard in many of my visualizations because my goal is generally to make many tweaks possible through simple inputs.

It can be as simple as breaking up, say, `DBBarPlot` into two internal functions of "making the `data.frame`" and "making the `ggplot`".  This basically cuts the function into two, which makes it easier for a reader - and for R's static analysis - to figure out what's happening; even if you have to pass the same set of arguments to both functions (though ideally one should be able to avoid this for many arguments).
