### ISSUE TITLE
Density plot functionality

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#45]
Density plots would be a nice addition via `stat_binhex()` and/or `stat_density_2d()`. Simplest implementation would likely be a new function built off of `dittoScatterPlot`, similar to how `dittoDimPlot` currently functions.

 An alternative would be to add a few additional parameters to `dittoScatterPlot` and build it out there. I think the former is probably less of a headache, but probably worth discussing.

**Comment by dtm2451** [comment]
For the underlying stat/geom:
I like the idea of `stat_binhex()` by default + `stat_density_2d()` when requested with something like `do.contour`.  Alternatively, or additionally only when `color` is requested, we could use `ggplot.multistats::geom_summaries_hex()` to show density through opacity, thus leaving color open for some other target variable.  But, I'll just admit now that I have almost zero experience using any of these, so ¯\_(ツ)_/¯. That's definitely why dittoSeq doesn't already have a hex-functionality.

For the implementation:
We could modify dittoScatterPlot to be the base, and it's what I'd always thought would happen. 
But looking into the geoms more, I don't love the idea because there are quite a few inputs in dittoScatterPlot that are not applicable. Also, if there end up being hex specific inputs, these would need to be exposed within the dittoScatterPlot doc. I think that all then gets confusing for users, so I don't like it.

Ultimately, no matter how we implement, we'll need to have a separate `.ditto_scatter_hex()` sub-function.  Otherwise it'd get super dirty because half the code in `.ditto_scatter_plot()` parses shape or color.  (Shape is useless for hexPlots, and coloring is implemented quite differently from `geom_point`, from what I can tell, for all hex geoms that handle it.)

So I propose we make a .scatter_data_gather() subfunction that would be shared between `dittoScatterPlot()` and a `dittoScatterHex()`. Then we can have `.ditto_scatter_hex()` build the plot with whatever geoms we choose.  And `dittoDimHex()` can wrap around all that similarly to `dittoDimPlot()`.

The "good news" here is that I don't think `dittoDimHex()` will have as many extra overlays as `dittoDimPlot()` -- really just the trajectory overlays -- so we could probably group `dittoScatterHex()` and `dittoDimHex()` together into a single piece of documentation.
