### ISSUE TITLE
Repel labels and ensure they are fully in the plot space

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/DittoSeq#7]
The labels for `dittoDimPlot` are really nice, but they can sometimes crowd each other or get cut off:
![image](https://user-images.githubusercontent.com/10225716/63068540-1b7f0280-bed9-11e9-8e4c-3f1958d93aaa.png)

This can be somewhat alleviated by adjusting `label.size`, but overlapping still occurs. Labels can't be moved in post (Illustrator), as the cells they cover seemingly aren't plotted. Adding a "repel" option and a check to ensure all labels are fully within the plotting area would be nice quality of life changes.

**Comment by dtm2451** [comment]
Hmmm these are things I'm not entirely sure how to fix so I could use help!

Preliminary fixes:

- Use coord_cartesian to adjust the zoom of the plot:  dittoDimPlot()/DBDimPlot() + coord_cartesian(xlim = c(-25,7))
- Turning the highlight off (`highlight.labels = FALSE`) is my usual fix for seeing through to points and labels underneath.  But that is obviously not ideal for final figures.  I had also not realized that the points are totally removed from the plot and inaccessible in Illustrator.  That is quite unfortunate!

I'm not sure how to code these myself, so I'd welcome help if you or anyone else can suggest the code for both:

- "repel"ing labels.
- determining when the plots extents need to be adjusted in order to fit all labels in.

**Comment by j-andrews7** [comment]
As we discussed, looks like [ggrepel](https://github.com/slowkow/ggrepel) can likely take care of both issues. If you don't get to it, I may take a crack at it this weekend or next week.

**Comment by dtm2451** [comment]
Wanna test my implementation when you get a chance?  It was super simple to implement ggrepel, thanks for the suggestion!

```
devtools::install_github("dtm2451/DittoSeq@development-labelsRepel")
```

I just checked with the code below, but would love to see if you like what it does for your data.  I don't provide all the datapoints to the ggrepel calls (just the groupings' centers... providing all datapoints would slow the calc down drastically for large datasets) so datapoints will likely still be covered up.  However the main goal of having the labels stay in-plot and non-overlapping should hopefully be fixed!

Example code:

```
library(DittoSeq)
example("dittoDimPlot")
pbmc@meta.data$BIGNAMES <- factor(meta("ident"), labels = (c("LONGLONGLONGLONG-0","LONGLONGLONGLONG-1","LONGLONGLONGLONG-2")))
dittoDimPlot("BIGNAMES")
dittoDimPlot("BIGNAMES", do.label = TRUE)
dittoDimPlot("BIGNAMES", do.label = TRUE, labels.repel = TRUE)
dittoDimPlot("BIGNAMES", do.label = TRUE, labels.repel = TRUE, highlight.labels = FALSE)
```

**Comment by j-andrews7** [comment]
With `labels.repel = FALSE`:
![image](https://user-images.githubusercontent.com/10225716/63231465-a87bd180-c1e1-11e9-968a-83449e138fb6.png)

Boo 👎 

With `labels.repel = TRUE`:
![image](https://user-images.githubusercontent.com/10225716/63231499-19bb8480-c1e2-11e9-9e9b-8c820d961927.png)

👍 💯
