### ISSUE TITLE
heatmap order by two levels of facrtors

### ISSUE THREAD

**Issue by gt7901b** [dtm2451/dittoSeq#70]
Hi, Daniel:

Is there a way to do heatmap order the columns by two levels of factors? for example, by sample and by cell type?

thanks

**Comment by dtm2451** [comment]
You can give custom ordering to the `order.by` input via the numeric input method. But I can't seem to get that right in order to provide you the code, so... there may be a bug there.

I'll 1) see if the numeric method is broken, and also 2) expand the metadata-name method to allow provision of multiple metadata.

**Comment by gt7901b** [comment]
Thanks for your reply, Daniel. I tried, 
order.by = c("SubjectID","clusternames") 
but got error.
is it possible first sort by sample, then sort by cell type with two color bars on top?

**Comment by dtm2451** [comment]
Right, no, not currently.  I haven't added this yet, but gimme a few days and I'll let you know how to install a version where `order.by = c("SubjectID","clusternames")` would work.

**Comment by dtm2451** [comment]
Hi @gt7901b,

I've now pushed an update/fix for this `order.by` input.

Because of the concurrent bug fix, I'm pushing this straight through to the release version of the package.  Sometime early next week (likely by Tuesday) it will propagate through the Bioconductor build system and then you would be able to grab the fix via the normal `Bioconductor::install("dittoSeq")` route.   In the meantime, you can use `Bioconductor::install("dtm2451/dittoSeq")`.

Please let me know, when you get a chance, if it works for your data!

And it was tangential to your request, but thanks for helping me discover the bug in the less commonly utilized side of this feature!

**Comment by gt7901b** [comment]
it works like a charm! thank you so much, Daniel!
