### ISSUE TITLE
Reorder levels from dimplot to dittobarplot

### ISSUE THREAD

**Issue by JaviTankian** [dtm2451/dittoSeq#73]
I have a very naive question regarding dittoBarplolt representation. I want to use the same order and colours in the UMAP and dittoBarplot (figure below), but i can´t. Do yoy know how can I apply the order and the colours of the UMAP figure in celltype proportion figure?
![figure](https://user-images.githubusercontent.com/32361535/110594669-64fb0680-817d-11eb-94ab-acde171d51f0.jpg)

Someone recomended me to change the order in Dimplot to match with the one in dittoBarplot, but I would like to use the specific order from Dimplot. Hence, I tried to change the level order of the cell type in dittoSeq but it is not clear for me how to do it. Can you help me please?

Many thanks

**Comment by dtm2451** [comment]
Hmm my first question was why the ordering was not automatically the same.  ASAIK, Seurat doesn't have any internal reordering mechanisms, so both functions should be using the same underlying data. And thus as long as you give the same thing to Seurat::DimPlot's `group.by` and dittoSeq::dittoBarPlot's `var` inputs, I'd intended that you would get the same ordering.

But it seems like factor-levels get dropped in the var-data in dittoBarPlot's data collection process.  This was not meant to happen, so I'll fix that for the next release, but in the meantime, you can use the `var.labels.reorder` input of dittoBarPlot.  

I think this should work:
```
dittoBarPlot(object = your_data_obj, var = "your_annotations_meta", ...,
    var.labels.reorder = order(levels(your_data_obj$your_annotations_meta)))
```
Or if you are giving "idents" to `var`, then it should be `order(levels(Idents(your_data_obj)))` instead.

Future fix:
- I'm going to fold the factor-level retention fix into the `split-by` branch, where I've already added to the dittoBarPlot data collection code for #72. I'll let you know once I do.

**Comment by cstrlln** [comment]
I tried the suggested solution but didn't work.

**Comment by dtm2451** [comment]
This issue should be fixed in the `split-by` branch.

Respect for factor-levels will become the default behavior in the next Bioconductor release (mid-May).  In the meantime, you can install the fix from GitHub with `BiocManager::install("dtm2451/dittoSeq@split-by")`.

@cstrlln I'm hopeful that the suggested fix above gave you issues because you had already installed from this branch and so were "doubly" fixing the issue?

In any case, PR #76 adds a `retain.factor.levels` input to `dittoBarPlot()` which is TRUE by default, but can be set to FALSE for anyone wanting to recreate their older plots faithfully.

Interested in hearing if this indeed works for both of you! @cstrlln & @JaviTankian
