### ISSUE TITLE
How to make heatmap legend smaller or multiple lines to include all?

### ISSUE THREAD

**Issue by Yale73** [dtm2451/dittoSeq#80]
Hi dittoSeq,

Thanks for such a great object-based plot package. 
I am using our `dittoHeatmap() `and there are 33 samples, but **the legend is too big to include all (only 22 are kept)**. Also, I annotated two factors (donor and dis) but only one legend (donor) can be retained. I tried the ggplot `theme()` and it doesn't work. Is there a way to make the legend smaller to include all the sample information?  
![image](https://user-images.githubusercontent.com/50378244/117501314-b7189800-af32-11eb-82af-fbae35b1bab9.png)

One more question: is there a function we can get the z-score to make the heatmap?

Thanks,
Yale

**Comment by dtm2451** [comment]
I'll actually answer this one first:
> One more question: is there a function we can get the z-score to make the heatmap?
Yes!  If you add `data.out = TRUE`, then instead of the rendered heatmap, you will get the list of inputs that would have been given to the heatmap rendering function.  The `mat` element will be *pre-z-scoring, but you could z-score it yourself. 

Passing those input through to a heatmap renderer -- either `pheatmap::pheatmap()` or if you in a newer version of dittoSeq and gave `complex = TRUE` then `ComplexHeatmap::pheatmap()`-- is actually the only remaining step of dittoHeatmap() after those inputs are generated.

So for your first set of questions:
Your plot looks like it's based on the `pheatmap::pheatmap()` option which I don't believe offers much legend control.  So unfortunately, unless you can 1) switch to ComplexHeatmap::pheatmap() by giving `complex = TRUE` which might offer some more control (but I'm not super well versed there myself!), all I can recommend is 2) outputting the heatmap in a larger size, or 3) saving it as a pdf and adjusting the legend manually in a pdf-editing software.

**Comment by Yale73** [comment]
@dtm2451 Hi, thanks for your quick reply. Mine is the latest dittoSeq (1.2.6). 
I used Rstudio and set the `data.out=TRUE`, but all the information displayed in the Console rather than a table. Can I save it and write a table for the `mat`?

Also, I tried to add complex=TRUE, and got the error: ```
Error in Cairo(width, height, type = "png", file = filename, pointsize = pointsize,  : 
  Failed to create Cairo backend!
```

I can save a large plot, but sometimes I don't have many genes and then the plot will be not beautiful. If it is the only way, I will use it, lol. 

Thanks,
Yale

**Comment by dtm2451** [comment]
Hi there,

Right, yea, I wish I had a better fallback answer than 'just make it large!' but heatmaps are unfortunately the only ditto-Viz's that are not ggplot-reliant.  They rely entirely on outside tools so I have a lot less control.  That said, the legend from ComplexHeatmaps have a very gpplot feel, and in my experience they do seem to try to fit better within your plotting window.  So I'd suggest trying to push through with that.

It looks like your `complex=TRUE` issue is with image manipulation software, `cairo`, that `ComplexHeatmap` relies on. There's basically an R package wrapper called [Cairo](https://cran.r-project.org/web/packages/Cairo/index.html), and I'd make sure that you have that installed. Should be just `install.packages("Cairo")`, but you may need to install the underlying cairo package from outside of R. 

For `data.out = TRUE`, the output is a named list.  So you can save it as an object... 
```
hm_args <- dittoHeatmap(..., data.out = TRUE)
```
And then
```
hm_args$mat
```
would be the matrix.

-Dan

**Comment by dtm2451** [comment]
I'm assuming this has been more or less resolved?  Feel free to reopen if not!
