### ISSUE TITLE
dittoFreqPlot variable outputs

### ISSUE THREAD

**Issue by SchulzDan** [dtm2451/dittoSeq#93]
Hi,
thanks for this really nice package! I came across the dittoFreqPlot function and I am not sure I understand what is going on in the back. I have an SingleCellExperiment objects and run the following code and get the subsequent plot:
dittoFreqPlot(sce,var="knn_10_spatial_clusters", group.by = "Therapy",sample.by = "ImageNumber")
![image](https://user-images.githubusercontent.com/18529618/127170222-ef9a3745-854e-4db0-9acf-8663635f991a.png)

when I run the functions with "retain.factor.levels = TRUE" the plot looks different and I checked and the numbers are correct in this version of the function:
dittoFreqPlot(sce,var="knn_10_spatial_clusters", group.by = "Therapy",sample.by = "ImageNumber", retain.factor.levels = TRUE)
![image](https://user-images.githubusercontent.com/18529618/127170602-4caffccb-552b-4a33-a3c4-f601b0c5cf62.png)

Could you explain what exactly "retain.factor.levels = TRUE" does? tricky to know which is the "correct" plot.
thanks and best,
daniel

**Comment by dtm2451** [comment]
Oof very sorry for the long delay!  Been swamped.  I'd noticed some oddness with `dittoFreqPlot()` and `retain.factor.levels` myself even before I released the function last cycle, but at the time, I'd believed the different looks to be just the result of a bunch of retained zero values.  On the contrary, your plots show completely different value outputs for non-zero data points.  Let me re-familiarize myself with the code and get back to you!

**Comment by dtm2451** [comment]
From the poking and thinking I've done so far: *I thinkkkk that the `retain.factor.levels = TRUE` version is likely to be more trustworthy from the look of your data*.  But the real answer is that I don't think the function accounts properly for important edge-cases, and thus the truth may be the neither are correct.

When `retain.factor.levels = FALSE` (the default), the `var` and `group.by` data are run through `as.character()`, which removes any notion of factor levels for those. Then, whenever a calculation of cell type frequency is run for a given sample, it is only run on combinations of `var` (cell types/ clusters) + `group.by` that actually exist in the data.  Thus, you can lose some valid zeros which would have represented a sample having zero cells of a certain cluster.  *But those zeros should be retained, so TRUE would be better.*  The flip side however, is that if a given sample is only ever part of one `group.by` group, a.k.a. "pre" vs "post" for you, `retain.factor.levels = TRUE` would lead to generation of zero values for that sample in the other `group.by` group(s). *Those zeros truly should be ignored, so FALSE would actually be better here!*

I need to do some more mapping of potential use / edge cases, followed by refactoring the calculation to account for all options.

Thanks so much for bringing this issue to my attention!!!

**Comment by SchulzDan** [comment]
thanks for looking into it!

**Comment by dtm2451** [comment]
I think I have the solution worked out, and I'll get to work on implementing it soon!

What I've realized is that there's a distinction between the level-saving needs of `var` versus `group.by` (and `color.by`, which I ignored it before, but it works similarly to `group.by`.)

- `var`: sets the potential cell types / clusters (/ any other discrete cellular feature that a user wants quantified and turned into a facet of these plots).  Even if a sample has zero cells of `var`-level, we still need to have those zeros calculated.  => For every sample, we should calculated a value for all possible options of `var-data`.  In terms of the current implementation, this means *`var`-data should always be treated as `retain.factor.levels = TRUE`*.
- `group.by` and `color.by`: define the sample classifications.  A sample may be part of multiple `group.by`(+`color.by`)-groupings, but it also may not.  *1) If samples truly should have cells within ALL grouping-levels, that's when the current `retain.factor.levels = TRUE` implementation is correct.  But 2) if samples are expected to exist within just a subset of the groupings, then we actually do want to ignore grouping-levels with zero cells!*  => There's actually no way for me/dittoSeq to reliably know the truth here, so I think I should keep the input, but set it to only affect these data.  A.k.a. For each sample, the function will always calculate for every cell type, but users would have control over whether calculations are run (/zeros are kept) for every grouping versus just groupings with cells of the given sample.

Some extra thoughts (which you may or may not care about lol): 
- I'll likely rename this parameter because it's not going to affect `var` factor levels, which means the current name would become confusing. But also because...
- After frequency calculations are completed, I'll likely add the factor levels back to the dataframe, because I think it's likely that even when a user wants group.by/color.by factors ignored, they'll still want the ordering, which is secondarily provided by those level definitions, retained!

**Comment by dtm2451** [comment]
Welp, I forgot about a scoping decision that I made previously, which actually simplifies things...

The function is implemented with the expectation that group.by data will always reflect some sort of sample characteristic, like "timepoint", "age", or "treatment-condition", for which the each sample of the sample.by data should only exist within 1 classification.  The function errors out with a message about that if you try to give inputs where samples would span multiple grouping conditions.

So that actually simplifies things to the point where I'll be getting rid of the `retain.factor.levels` user control here completely.  It needs to always need to be `TRUE` for `var`, as explained before, and `FALSE` for `group.by` (= "calculate only for groups where the sample exists, and because each sample does only exist in a single group, calculating for any other groups will always lead to unwanted zeros!).

Sorry for my wordiness as I've been working through what to do =p.

The fix is implemented now in the above PR.

Until I get it merged in, you can install with `BiocManager::install("dtm2451/dittoSeq@FreqPlot-factor-levels")` to use the fixed version of the function.

**Comment by dtm2451** [comment]
Finished the PR and pushed to Bioc.  Both devel and release as this is an important bug fix!  Assuming no issues on the build system, given the build schedule, it'll be included in standard dittoSeq installs by Wednesday.
